### ISSUE TITLE
ieo.py convertespatotiles - 2

### ISSUE THREAD

**Issue by JRGZ** [DrGuy/ieo#10]
I came across a problem where a downloaded Landsat 7 product (LE070802220190913) wasn't listed in the landsat geopackage (how this is possible I don't know, as I understand the geopackage is use to create the download list). This crashed the script so I think it might e a good idea to include a try/except fail safe for line 1332 in case the while-loop fails to find a scence id.

**Comment by DrGuy** [comment]
So there have been several updated since then- hopefully it has been fixed!
